version: "3.8"

services:
  web:
    build:
      dockerfile: docker/Dockerfile
      context: .
    restart: unless-stopped
    ports:
      - "8000"
    environment:
      APP_ENV: ${APP_ENV:-dev}
    volumes:
      - ${PWD}/backend/:/opt/code
    networks:
      - web

  reverse_proxy:
    image: nginx:1.21-alpine
    volumes:
      - ${PWD}/docker/nginx/app.conf:/etc/nginx/conf.d/default.conf
      - ${PWD}/web:/opt/react
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      - web

networks:
  web:
