version: "3.8"

services:
  web:
    build:
      dockerfile: docker/Dockerfile
      context: .
    restart: unless-stopped
    ports:
      - "8000"
    environment:
      APP_ENV: ${APP_ENV:-dev}
    volumes:
      - ${PWD}/backend/:/opt/code
    networks:
      - web
      - database

  reverse_proxy:
    image: nginx:1.21-alpine
    restart: always
    volumes:
      - ${PWD}/docker/nginx/app.conf:/etc/nginx/conf.d/default.conf
      - ${PWD}/web:/opt/react
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      - web
  db:
    image: mongo:5.0
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD:-example}
    volumes:
      - ./data/mongo:/data/db
    networks:
      - database

networks:
  web:
  database:
